### ISSUE TITLE
Only ascii compatible?

### ISSUE THREAD

**Issue by xNxExOx** [Blakeinstein/fuse-rust#10]
https://github.com/Blakeinstein/fuse-rust/blob/master/src/lib.rs#L206
```rs
fn search_util(&amp;self, pattern: &amp;Pattern, string: &amp;str) -&gt; ScoreResult {
    let string = if self.is_case_sensitive {
        String::from(string)
    } else {
        string.to_ascii_lowercase()
    };
``
is this supposed to be only ascii?

**Comment by Blakeinstein** [comment]
No... Multi byte chars should work.

There is a test for this as well
https://github.com/Blakeinstein/fuse-rust/blob/c6854b72e2a48ff3f384abfaa9f44b34fca0c61f/src/tests.rs#L4-L19

**Comment by Blakeinstein** [comment]
Closing due to lack of response
