### ISSUE TITLE
Panic of long patterns

### ISSUE THREAD

**Issue by l4l** [Blakeinstein/fuse-rust#9]
The following code

```rust
Fuse::default().create_pattern("qweqweqweqweqweqweqweqweqweqweqwe"); // 33 bytes, as you may guess
```

leads to this panic:

```
thread 'main' panicked at 'attempt to shift left with overflow', fuse-rust-0.1.4/src/utils.rs:20
```

Bigger values of  `Fuse.max_pattern_length` doesn't help as well.

**Comment by Blakeinstein** [comment]
I will fix this with the rewrite. I have my exams rn, and I cant do much before 25th.

**Comment by Blakeinstein** [comment]
I have implemented a fix for this, I am closing this for now. Expect this to be merged to release along with multi-byte char searching.
